import unittest
import pandas as pd
import numpy as np
import os
import sys
from uuid import uuid4
from unittest.mock import MagicMock, patch

# Add backend to path
sys.path.append(os.path.join(os.getcwd()))

from app.services.anonymizer import Anonymizer
from app.models.schemas import AnonymizationTechnique, DataType, Category

class TestLabelConsistency(unittest.TestCase):
    def setUp(self):
        self.db = MagicMock()
        self.anonymizer = Anonymizer(self.db)
        
        # Test data
        self.data = {
            "SSN": ["123-456-789", "987-654-321"],
            "BIRTHDATE": ["1990-05-15", "1985-11-20"],
            "RACE": ["white", "black"],
            "GENDER": ["male", "female"],
            "ZIP": ["12345", "67890"],
            "ADDRESS": ["123 Main St", "456 Oak Ave"],
            "HEALTHCARE_EXPENSES": [1200.50, 4500.00],
            "OTHER": ["Some text", "Other text"]
        }
        self.df = pd.DataFrame(self.data)
        
    @patch('app.services.data_ingestion.DataIngestionService.load_dataframe')
    @patch('app.services.anonymizer.Anonymizer.anonymize_dataset')
    @patch('app.services.ai_enhanced_detector.AIEnhancedDetector.analyze_dataset')
    async def test_auto_anonymize_logic_alignment(self, mock_analyze, mock_anonymize, mock_load):
        # Mocking detection report
        class MockCls:
            def __init__(self, sens, cat):
                self.sensitivity_type = sens
                self.category = cat
                self.confidence = 100
                self.suggested_config = None

        mock_analyze.return_value = MagicMock(columns={
            "SSN": MockCls(DataType.DIRECT_IDENTIFIER, Category.PERSONAL),
            "BIRTHDATE": MockCls(DataType.QUASI_IDENTIFIER, Category.PERSONAL),
            "RACE": MockCls(DataType.QUASI_IDENTIFIER, Category.PERSONAL),
            "GENDER": MockCls(DataType.QUASI_IDENTIFIER, Category.PERSONAL),
            "ZIP": MockCls(DataType.QUASI_IDENTIFIER, Category.PERSONAL),
            "ADDRESS": MockCls(DataType.QUASI_IDENTIFIER, Category.PERSONAL),
            "HEALTHCARE_EXPENSES": MockCls(DataType.SENSITIVE, Category.HEALTH),
            "OTHER": MockCls(DataType.NON_SENSITIVE, Category.OTHER)
        })
        
        mock_load.return_value = self.df
        
        # We want to test what configurations are generated by auto_anonymize
        # Since it returnsAnonymizationResponse, we check the 'configs' used in anonymize_dataset call
        
        dataset_id = uuid4()
        try:
            await self.anonymizer.auto_anonymize(dataset_id)
        except Exception:
            pass # We just care about the calls made to mock_anonymize
            
        # Get the config sent to anonymize_dataset
        # mock_anonymize.call_args[0][1] is the List[AnonymizationConfig]
        configs = mock_anonymize.call_args[0][1]
        config_map = {c.column_name: c for c in configs}
        
        print("\n--- Logic Verification ---")
        
        # 1. SSN -> Suppression
        self.assertEqual(config_map["SSN"].technique, AnonymizationTechnique.SUPPRESSION)
        print("SSN: Suppression OK")
        
        # 2. BIRTHDATE -> Generalization (Year)
        self.assertEqual(config_map["BIRTHDATE"].technique, AnonymizationTechnique.GENERALIZATION)
        self.assertEqual(config_map["BIRTHDATE"].params["mode"], "year")
        print("BIRTHDATE: Year-only OK")
        
        # 3. RACE -> Generalization (Hierarchy)
        self.assertEqual(config_map["RACE"].technique, AnonymizationTechnique.GENERALIZATION)
        self.assertIn("hierarchy", config_map["RACE"].params)
        print("RACE: Category Grouping OK")
        
        # 4. ZIP -> Generalization (Range)
        self.assertEqual(config_map["ZIP"].technique, AnonymizationTechnique.GENERALIZATION)
        self.assertEqual(config_map["ZIP"].params["mode"], "range")
        print("ZIP: Geo generalization OK")
        
        # 5. ADDRESS -> Suppression
        self.assertEqual(config_map["ADDRESS"].technique, AnonymizationTechnique.SUPPRESSION)
        print("ADDRESS: Suppression OK")
        
        # 6. HEALTHCARE_EXPENSES -> DP
        self.assertEqual(config_map["HEALTHCARE_EXPENSES"].technique, AnonymizationTechnique.DIFFERENTIAL_PRIVACY)
        print("HEALTHCARE_EXPENSES: Differential Privacy OK")

if __name__ == "__main__":
    import asyncio
    
    # Run async test manually for simplicity in this environment
    test = TestLabelConsistency()
    test.setUp()
    
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test.test_auto_anonymize_logic_alignment())
    print("\nConsistency Verification PASSED!")
